version: "3"
services:
    web:
        build: .
        ports:
            - "5000:5000"
        networks:
            - todo
        volumes:
            - ./src:/app
    db:
        image: mongo:3.0.15
        networks:
            - todo
        volumes:
            - "mongo-data:/data/db"
networks:
    todo:

volumes:
    mongo-data:
